<?php
/**
* Implements hook_block_info()
*/
function portfolio_overview_block_info() {
	$blocks['overview'] = array(
		'info' => 'Portfolio Overview',
	);
	return $blocks;
}

/**
* Implements hook_block_view()
*/
function portfolio_overview_block_view($delta = '') {
	$block = array();
	if ($delta == 'overview') {
		$block['subject'] = 'Portfolio at a Glance';
		$block['content'] = portfolio_overview_output();
	}
	return $block;
}

function portfolio_overview_output() {
	$blog_ct = db_query("SELECT COUNT(nid) FROM node WHERE type = 'blog_post'")->fetchColumn();
	$bdg_ct = db_query("SELECT COUNT(nid) FROM node WHERE type = 'badge'")->fetchColumn();
	$tx_ct = db_query("SELECT COUNT(tid) FROM taxonomy_term_data WHERE vid = 1")->fetchColumn();
	$proj_ct = db_query("SELECT COUNT(nid) FROM node WHERE type = 'project'")->fetchColumn();

	$output = '<h3>' . $blog_ct . ' blog posts</h3>';
	$output .= '<h3>' . $bdg_ct . ' badges</h3>';
	$output .= '<h3> ' . $tx_ct . ' skills in progress</h3>';
	$output .= '<h3>' . $proj_ct . ' projects to show off</h3>';
	return $output;
}

?>